// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as MongoCodecTypes, Vector } from '@prisma/orm-mongo/adapter/codec-types';

import type {
  MongoCollection,
  MongoContractWithTypeMaps,
  MongoTypeMaps,
  RelationKeys,
} from '@prisma/orm-mongo/family-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-mongo/contract/types';

export type StorageHash =
  StorageHashBase<'f8ec32331bf14df85af2be78842e4bd22ba3de422af6295e3d1cc3874fba4f95'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'251b3ce23f6c9f561892e7c1af9d2cc941a13d64ba1aa7226b90036b09568cc3'>;

export type CodecTypes = MongoCodecTypes;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly AboutContent: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly content: CodecTypes['mongo/string@1']['output'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['output'] | null;
      readonly section: CodecTypes['mongo/string@1']['output'] | null;
      readonly updatedAt: CodecTypes['mongo/date@1']['output'] | null;
    };
    readonly Admin: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly createdAt: CodecTypes['mongo/date@1']['output'] | null;
      readonly email: CodecTypes['mongo/string@1']['output'] | null;
      readonly fullName: CodecTypes['mongo/string@1']['output'] | null;
      readonly passwordHash: CodecTypes['mongo/string@1']['output'] | null;
      readonly role: CodecTypes['mongo/string@1']['output'] | null;
      readonly updatedAt: CodecTypes['mongo/date@1']['output'] | null;
    };
    readonly BlogPost: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly content: CodecTypes['mongo/string@1']['output'] | null;
      readonly coverImage: CodecTypes['mongo/string@1']['output'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['output'] | null;
      readonly excerpt: CodecTypes['mongo/string@1']['output'] | null;
      readonly published: CodecTypes['mongo/bool@1']['output'] | null;
      readonly publishedAt: CodecTypes['mongo/date@1']['output'] | null;
      readonly readingTime: CodecTypes['mongo/int32@1']['output'] | null;
      readonly slug: CodecTypes['mongo/string@1']['output'] | null;
      readonly tags: ReadonlyArray<CodecTypes['mongo/string@1']['output']> | null;
      readonly title: CodecTypes['mongo/string@1']['output'] | null;
      readonly updatedAt: CodecTypes['mongo/date@1']['output'] | null;
    };
    readonly Experience: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly createdAt: CodecTypes['mongo/date@1']['output'] | null;
      readonly description: CodecTypes['mongo/string@1']['output'] | null;
      readonly order: CodecTypes['mongo/int32@1']['output'] | null;
      readonly tags: ReadonlyArray<CodecTypes['mongo/string@1']['output']> | null;
      readonly title: CodecTypes['mongo/string@1']['output'] | null;
      readonly updatedAt: CodecTypes['mongo/date@1']['output'] | null;
      readonly year: CodecTypes['mongo/int32@1']['output'] | null;
    };
    readonly Project: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly caseStudyUrl: CodecTypes['mongo/string@1']['output'] | null;
      readonly category: CodecTypes['mongo/string@1']['output'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['output'] | null;
      readonly description: CodecTypes['mongo/string@1']['output'] | null;
      readonly imageUrl: CodecTypes['mongo/string@1']['output'] | null;
      readonly liveUrl: CodecTypes['mongo/string@1']['output'] | null;
      readonly order: CodecTypes['mongo/int32@1']['output'] | null;
      readonly published: CodecTypes['mongo/bool@1']['output'] | null;
      readonly slug: CodecTypes['mongo/string@1']['output'] | null;
      readonly sourceUrl: CodecTypes['mongo/string@1']['output'] | null;
      readonly tags: ReadonlyArray<CodecTypes['mongo/string@1']['output']> | null;
      readonly title: CodecTypes['mongo/string@1']['output'] | null;
      readonly updatedAt: CodecTypes['mongo/date@1']['output'] | null;
      readonly visual: CodecTypes['mongo/string@1']['output'] | null;
    };
    readonly StackItem: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly category: CodecTypes['mongo/string@1']['output'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['output'] | null;
      readonly name: CodecTypes['mongo/string@1']['output'] | null;
      readonly order: CodecTypes['mongo/int32@1']['output'] | null;
      readonly updatedAt: CodecTypes['mongo/date@1']['output'] | null;
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly AboutContent: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly content: CodecTypes['mongo/string@1']['input'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['input'] | null;
      readonly section: CodecTypes['mongo/string@1']['input'] | null;
      readonly updatedAt: CodecTypes['mongo/date@1']['input'] | null;
    };
    readonly Admin: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly createdAt: CodecTypes['mongo/date@1']['input'] | null;
      readonly email: CodecTypes['mongo/string@1']['input'] | null;
      readonly fullName: CodecTypes['mongo/string@1']['input'] | null;
      readonly passwordHash: CodecTypes['mongo/string@1']['input'] | null;
      readonly role: CodecTypes['mongo/string@1']['input'] | null;
      readonly updatedAt: CodecTypes['mongo/date@1']['input'] | null;
    };
    readonly BlogPost: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly content: CodecTypes['mongo/string@1']['input'] | null;
      readonly coverImage: CodecTypes['mongo/string@1']['input'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['input'] | null;
      readonly excerpt: CodecTypes['mongo/string@1']['input'] | null;
      readonly published: CodecTypes['mongo/bool@1']['input'] | null;
      readonly publishedAt: CodecTypes['mongo/date@1']['input'] | null;
      readonly readingTime: CodecTypes['mongo/int32@1']['input'] | null;
      readonly slug: CodecTypes['mongo/string@1']['input'] | null;
      readonly tags: ReadonlyArray<CodecTypes['mongo/string@1']['input']> | null;
      readonly title: CodecTypes['mongo/string@1']['input'] | null;
      readonly updatedAt: CodecTypes['mongo/date@1']['input'] | null;
    };
    readonly Experience: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly createdAt: CodecTypes['mongo/date@1']['input'] | null;
      readonly description: CodecTypes['mongo/string@1']['input'] | null;
      readonly order: CodecTypes['mongo/int32@1']['input'] | null;
      readonly tags: ReadonlyArray<CodecTypes['mongo/string@1']['input']> | null;
      readonly title: CodecTypes['mongo/string@1']['input'] | null;
      readonly updatedAt: CodecTypes['mongo/date@1']['input'] | null;
      readonly year: CodecTypes['mongo/int32@1']['input'] | null;
    };
    readonly Project: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly caseStudyUrl: CodecTypes['mongo/string@1']['input'] | null;
      readonly category: CodecTypes['mongo/string@1']['input'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['input'] | null;
      readonly description: CodecTypes['mongo/string@1']['input'] | null;
      readonly imageUrl: CodecTypes['mongo/string@1']['input'] | null;
      readonly liveUrl: CodecTypes['mongo/string@1']['input'] | null;
      readonly order: CodecTypes['mongo/int32@1']['input'] | null;
      readonly published: CodecTypes['mongo/bool@1']['input'] | null;
      readonly slug: CodecTypes['mongo/string@1']['input'] | null;
      readonly sourceUrl: CodecTypes['mongo/string@1']['input'] | null;
      readonly tags: ReadonlyArray<CodecTypes['mongo/string@1']['input']> | null;
      readonly title: CodecTypes['mongo/string@1']['input'] | null;
      readonly updatedAt: CodecTypes['mongo/date@1']['input'] | null;
      readonly visual: CodecTypes['mongo/string@1']['input'] | null;
    };
    readonly StackItem: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly category: CodecTypes['mongo/string@1']['input'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['input'] | null;
      readonly name: CodecTypes['mongo/string@1']['input'] | null;
      readonly order: CodecTypes['mongo/int32@1']['input'] | null;
      readonly updatedAt: CodecTypes['mongo/date@1']['input'] | null;
    };
  };
};

export namespace Models {
  export type unbound_AboutContent = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    content: CodecTypes['mongo/string@1']['output'] | null;
    createdAt: CodecTypes['mongo/date@1']['output'] | null;
    section: CodecTypes['mongo/string@1']['output'] | null;
    updatedAt: CodecTypes['mongo/date@1']['output'] | null;
    readonly [RelationKeys]?: never;
  };
  export type unbound_Admin = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    createdAt: CodecTypes['mongo/date@1']['output'] | null;
    email: CodecTypes['mongo/string@1']['output'] | null;
    fullName: CodecTypes['mongo/string@1']['output'] | null;
    passwordHash: CodecTypes['mongo/string@1']['output'] | null;
    role: CodecTypes['mongo/string@1']['output'] | null;
    updatedAt: CodecTypes['mongo/date@1']['output'] | null;
    readonly [RelationKeys]?: never;
  };
  export type unbound_BlogPost = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    content: CodecTypes['mongo/string@1']['output'] | null;
    coverImage: CodecTypes['mongo/string@1']['output'] | null;
    createdAt: CodecTypes['mongo/date@1']['output'] | null;
    excerpt: CodecTypes['mongo/string@1']['output'] | null;
    published: CodecTypes['mongo/bool@1']['output'] | null;
    publishedAt: CodecTypes['mongo/date@1']['output'] | null;
    readingTime: CodecTypes['mongo/int32@1']['output'] | null;
    slug: CodecTypes['mongo/string@1']['output'] | null;
    tags: ReadonlyArray<CodecTypes['mongo/string@1']['output']> | null;
    title: CodecTypes['mongo/string@1']['output'] | null;
    updatedAt: CodecTypes['mongo/date@1']['output'] | null;
    readonly [RelationKeys]?: never;
  };
  export type unbound_Experience = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    createdAt: CodecTypes['mongo/date@1']['output'] | null;
    description: CodecTypes['mongo/string@1']['output'] | null;
    order: CodecTypes['mongo/int32@1']['output'] | null;
    tags: ReadonlyArray<CodecTypes['mongo/string@1']['output']> | null;
    title: CodecTypes['mongo/string@1']['output'] | null;
    updatedAt: CodecTypes['mongo/date@1']['output'] | null;
    year: CodecTypes['mongo/int32@1']['output'] | null;
    readonly [RelationKeys]?: never;
  };
  export type unbound_Project = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    caseStudyUrl: CodecTypes['mongo/string@1']['output'] | null;
    category: CodecTypes['mongo/string@1']['output'] | null;
    createdAt: CodecTypes['mongo/date@1']['output'] | null;
    description: CodecTypes['mongo/string@1']['output'] | null;
    imageUrl: CodecTypes['mongo/string@1']['output'] | null;
    liveUrl: CodecTypes['mongo/string@1']['output'] | null;
    order: CodecTypes['mongo/int32@1']['output'] | null;
    published: CodecTypes['mongo/bool@1']['output'] | null;
    slug: CodecTypes['mongo/string@1']['output'] | null;
    sourceUrl: CodecTypes['mongo/string@1']['output'] | null;
    tags: ReadonlyArray<CodecTypes['mongo/string@1']['output']> | null;
    title: CodecTypes['mongo/string@1']['output'] | null;
    updatedAt: CodecTypes['mongo/date@1']['output'] | null;
    visual: CodecTypes['mongo/string@1']['output'] | null;
    readonly [RelationKeys]?: never;
  };
  export type unbound_StackItem = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    category: CodecTypes['mongo/string@1']['output'] | null;
    createdAt: CodecTypes['mongo/date@1']['output'] | null;
    name: CodecTypes['mongo/string@1']['output'] | null;
    order: CodecTypes['mongo/int32@1']['output'] | null;
    updatedAt: CodecTypes['mongo/date@1']['output'] | null;
    readonly [RelationKeys]?: never;
  };
}

export declare const models: {
  __unbound__: {
    AboutContent: Models.unbound_AboutContent;
    Admin: Models.unbound_Admin;
    BlogPost: Models.unbound_BlogPost;
    Experience: Models.unbound_Experience;
    Project: Models.unbound_Project;
    StackItem: Models.unbound_StackItem;
  };
};

export type TypeMaps = MongoTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'mongo-database';
        readonly entries: {
          readonly collection: {
            readonly about_content: MongoCollection;
            readonly admins: MongoCollection;
            readonly blog_posts: MongoCollection;
            readonly experience: MongoCollection;
            readonly projects: MongoCollection;
            readonly stack_items: MongoCollection;
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: {
    readonly about_content: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'AboutContent';
    };
    readonly admins: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Admin' };
    readonly blog_posts: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'BlogPost';
    };
    readonly experience: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Experience';
    };
    readonly projects: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Project';
    };
    readonly stack_items: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'StackItem';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly AboutContent: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly content: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly section: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly updatedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'about_content' };
          };
          readonly Admin: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly createdAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly email: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly fullName: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly passwordHash: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly role: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly updatedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'admins' };
          };
          readonly BlogPost: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly content: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly coverImage: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly excerpt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly published: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/bool@1' };
              };
              readonly publishedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly readingTime: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly slug: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly tags: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
                readonly many: true;
              };
              readonly title: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly updatedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'blog_posts' };
          };
          readonly Experience: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly createdAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly order: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly tags: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
                readonly many: true;
              };
              readonly title: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly updatedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly year: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'experience' };
          };
          readonly Project: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly caseStudyUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly category: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly imageUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly liveUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly order: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly published: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/bool@1' };
              };
              readonly slug: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly sourceUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly tags: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
                readonly many: true;
              };
              readonly title: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly updatedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly visual: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'projects' };
          };
          readonly StackItem: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly category: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly order: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly updatedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'stack_items' };
          };
        };
      };
    };
  };
  readonly capabilities: {};
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
